// todo-list-vue/src/components/TodoList.vue
<script setup lang="ts">
import { store } from "../composables/useStore";
import { Todo } from "../core/models/Todo";
import TodoListItem from "./TodoListItem.vue"
</script>

<template>
<div class="">
  <div class="divide-y">
    <TodoListItem v-for="todo of store.todoList.list" :key="todo.id" :todo="(todo as Todo)"/>
  </div>
</div>
</template>

// todo-list-react/src/components/TodoList.tsx
import { useStore } from "../hooks/useStore";
import { TodoListItem } from "./TodoListItem";

export function TodoListComponent() {
  const todoList = useStore((state) => state.todoList);

  return (
    <div className="">
      <div className="divide-y">
        {todoList.list.map((todo) => (
          <TodoListItem todo={todo} key={todo.id} />
        ))}
      </div>
    </div>
  );
}
