// todo-list-react/src/App.tsx
import { TodoAdd } from "./components/TodoAdd";
import { TodoListComponent } from "./components/TodoList";
import { useLoadTodos } from "./hooks/useLoadTodos";

function App() {
  useLoadTodos();
  return (
    <div className="w-full sm:w-[768px] mx-auto mt-4 p-4 border">
      <TodoAdd />
      <TodoListComponent />
    </div>
  );
}

export default App;

// todo-list-vue/src/App.vue
<script setup lang="ts">
import { onMounted } from "vue";
import TodoAdd from "./components/TodoAdd.vue";
import TodoList from "./components/TodoList.vue"
import { getTodoListUseCase } from "./dependencies.ts"
import { store } from "./composables/useStore.ts";

onMounted(() => {
  getTodoListUseCase.execute({
    next:({data}) => {
      if (data) store.setTodoList(data)
    }
  })
  })
  
</script>

<template>
<div class="w-full sm:w-[768px] mx-auto mt-4 p-4 border">
  <TodoAdd />
  <TodoList />
</div>

</template>

<style scoped></style>
